name: CI for Docker Hub

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Generate SSH Key
        run: |
          ssh-keygen -t ed25519 -P "" -f ~/.ssh/id_ed25519
          echo ~/.ssh/id_ed25519 > "$SSH_PRIVATE_KEY"
          echo  ~/.ssh/id_ed25519.pub > "$DEPLOY_SSH_KEY" 
          chmod 700 ~/.ssh
          chmod 600 ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519.pub
          cat $SSH_PRIVATE_KEY
          cat $DEPLOY_SSH_KEY
        
