name: Your Workflow Name

on:
  push:
    branches:
      - main

jobs:
  your-job-name:
    runs-on: ubuntu-latest  # Replace with your runner label
    
    steps:
      - name: Check if SSH key exists
        run: |
          if [ ! -f ~/.ssh/id_ed25519 ]; then
            ssh-keygen -t ed25519 -P "" -f ~/.ssh/id_ed25519
          fi
          cat ~/.ssh/id_ed25519.pub
