name: Your Workflow Name

on:
  push:
    branches:
      - main

jobs:
  your-job-name:
    runs-on: ubuntu-latest
    
    steps:
      - name: Generate and Use SSH Key
        env:
          SSH_PUBLIC_KEY_PATH: ~/.ssh/id_ed25519.pub
          SSH_PRIVATE_KEY_PATH: ~/.ssh/id_ed25519
        run: |
          # Check if the private key already exists
          if [ ! -f $SSH_PRIVATE_KEY_PATH ]; then
            ssh-keygen -t ed25519 -N "" -f $SSH_PRIVATE_KEY_PATH
          fi
          # Display the public key
          cat $SSH_PUBLIC_KEY_PATH
