name: CI for Docker Hub

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up SSH key
        run: |
          mkdir -p $HOME/.ssh
          echo $SSH_PUBLIC_KEY >> $HOME/.ssh/id_ed25519
          chmod 700 $HOME/.ssh
          chmod 700 $HOME/.ssh/id_ed25519

      - name: Docker login
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD

      - name: Build Docker image
        run: |
          docker build -t emihamza/go-web-server .

      - name: Push Docker image
        run: |
          docker push emihamza/go-web-server

      - name: Deploy application
        run: |
          ssh ip172-18-0-53-cksntcmfml8g00chl410@direct.labs.play-with-docker.com "docker stack deploy --compose-file docker-compose.yml myapp"
