name: Generate and Store SSH Keys

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      SSH_PUBLIC_KEY: ${{ secrets.DEPLOY_SSH_KEY }}

    steps:
      - name: Generate SSH Keys
        id: generate_ssh_keys
        run: |
          ssh-keygen -t ed25519 -P "" -f id_ed25519
          id_ed25519_contents=$(cat id_ed25519)
          id_ed25519_pub_contents=$(cat id_ed25519.pub)
          echo "::set-output name=SSH_PRIVATE_KEY_CONTENT::$id_ed25519_contents"
          echo "::set-output name=SSH_PUBLIC_KEY_CONTENT::$id_ed25519_pub_contents"

      - name: Store SSH Keys in Secrets
        run: |
          echo "$SSH_PRIVATE_KEY" > /tmp/ssh_private_key
          echo "$SSH_PUBLIC_KEY" > /tmp/ssh_public_key
          echo "Storing SSH Private Key in Secret"
          echo "$SSH_PRIVATE_KEY" | gh secret set SSH_PRIVATE_KEY --body -
          echo "Storing SSH Public Key in Secret"
          echo "$SSH_PUBLIC_KEY" | gh secret set SSH_PUBLIC_KEY --body -
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Display SSH Keys
        run: |
          echo "SSH Private Key:"
          cat /tmp/ssh_private_key
          echo "SSH Public Key:"
          cat /tmp/ssh_public_key
