name: CI for Docker Hub

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

 
      - name: Generate SSH Key
        run: |
          ssh-keygen -t ed25519 -P "" -f ~/.ssh/id_ed25519
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_ed25519
          echo "$DEPLOY_SSH_KEY" > ~/.ssh/id_ed25519.pub
          chmod 700 ~/.ssh
          chmod 600 ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519.pub
        env:
          DEPLOY_SSH_KEY: ${{ secrets.DEPLOY_SSH_KEY }}
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

      
      - name: Docker login
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD

      - name: Build Docker image
        run: |
          docker build -t emihamza/go-web-server .

      - name: Push Docker image
        run: |
          docker push emihamza/go-web-server

      - name: Create SSH directory
        run: mkdir -p ~/.ssh
      - name: Create known_hosts file
        run: touch ~/.ssh/known_hosts
      - name: Add host key to known_hosts
        run: 
          ssh-keyscan -H 20.228.211.183 >> ~/.ssh/known_hosts
          ssh-keyscan direct.labs.play-with-docker.com >> $HOME/.ssh/known_hosts
   
      - name: List files in ~/.ssh directory
        run: ls -la ~/.ssh
      - name: SSH to the server
        run: ssh ip172-18-0-9-cktct3ksnmng00b3gav0@direct.labs.play-with-docker.com "docker stack deploy --compose-file docker-compose.yml myapp"
