name: CI for Docker Hub

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Generate SSH Key
        run: |
          ssh-keygen -t ed25519 -P "" -f ~/.ssh/id_ed25519
          echo "$SSH_PRIVATE_KEY" | tr -d '\r' > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          cat ~/.ssh/id_ed25519
        env:
          SSH_PRIVATE_KEY: ${{ secrets.DEPLOY_SSH_KEY }}

      
      - name: Create known_hosts file
        run: |
          touch ~/.ssh/known_hosts
          ls -l ~/.ssh/known_hosts

      - name: Docker login
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD

      - name: Build Docker image
        run: |
          docker build -t emihamza/go-web-server .

      - name: Push Docker image
        run: |
          docker push emihamza/go-web-server

      - name: Deploy application
        run: |
          ssh -i ~/.ssh/id_ed25519 root@192.168.0.28 "docker stack deploy --compose-file docker-compose.yml myapp"
